config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  # resources :tasks
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id/edit', to:'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to:'tasks#update'
  delete 'tasks/:id', to:'tasks#destroy', as: 'task'
  get 'tasks/:id', to: 'tasks#show'
  post 'tasks', to: 'tasks#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @tasks = current_user.tasks
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
     @task = current_user.tasks.create(task_params) 
    #  @task.user = current_user
     redirect_to(root_path)   
  end

  def edit
    @task = Task.find(params[:id]) 
  end

  def update
    @task = Task.find(params[:id]) 
    @task.update(task_params)
    redirect_to(root_path)   
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to(root_path)
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
       Welcome <%= current_user.email%>&nbsp; | &nbsp;<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>  
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back',root_path %>

app/views/tasks/index.html.erb
<h1>Your Tasks </h1>
<hr>
<% @tasks.each_with_index do |task,i| %>
  <li><%=i+1 %>.&nbsp;<%= task.name %> | <%= link_to 'Delete', task_path(task), method: :delete %> | <%= link_to 'Edit', task_edit_path(task)%> </li>
<% end %>
<button><%= link_to "Add New Task", tasks_new_path  %></button>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= form_with model: @task do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back',root_path %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p><%= params[:id] %></p>